accounts/urls.py
from django.urls import path
from .views import Login, RegisterUser, Logout

#Urls here 
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

devserver/urls.py
from django.contrib import admin
from django.views import generic
from django.urls import path, include
from django.contrib.auth.mixins import LoginRequiredMixin

# Home view
class Home(LoginRequiredMixin, generic.TemplateView):

    # Template
    template_name = 'devserver/home.html'


urlpatterns = [
    path('admin/', admin.site.urls),

    # Home url
    path('', Home.as_view(), name='home'),

    # Admin dashboard
    path('admin_dashboard/', include('admin_dashboard.urls', namespace='admin_dashboard')),

    # Accounts URLS
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # File upload
    path('file_upload/', include('file_upload.urls', namespace='file_upload')),

    # File download
    path('file_download/', include('file_download.urls', namespace='file_download')),

    # Taxi Log
    path('taxi_log/', include('taxi_log.urls', namespace='taxi_log')),

    # API endpoints for use by the form creator 
    path('api/', include('form_creator_api.urls', namespace='form_creator_api'))
]

taxi_log/urls.py
from . import views 
from django.urls import path

app_name = 'taxi_log'

urlpatterns = [
    path('', views.TaxiOrderList.as_view(), name='order_list_view'),
    path('order/', views.CreateOrder.as_view(), name='create_order'),
    path('order/<int:pk>/', views.UpdateOrder.as_view(), name='update_order'),
    path('pdf_view/<str:date>/', views.TaxiOrderListPDF.as_view(), name='order_list_pdf_view'),
    path('pdf_download/<str:date>/', views.TaxiOrderListPDFDownload.as_view(), name='order_list_pdf_download_view')
]

taxi_log/models.py
from django.db import models
from django.urls import reverse 
from django.contrib.auth.models import User

# Create your models here.

#Taxi order class
class TaxiOrder(models.Model):
    
    #Request log id
    request_log_id = models.PositiveIntegerField(blank=False, null=True)
    
    #Auto generated order number 
    order_number = models.PositiveIntegerField(null=False, blank=False)

    #Confirmation number
    confirmation_number = models.PositiveIntegerField(null=True, blank=False)
    
    #Date created 
    date_created = models.DateTimeField(auto_now_add=True)

    #User who created this order
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    #Redirect
    def get_absolute_url(self):
        return reverse('taxi_log:order_list_view')
    
    #Str 
    def __str__(self):
        return str( self.order_number )

taxi_log/forms.py
from django import forms

from .models import TaxiOrder

#Order form
class OrderForm(forms.ModelForm):
    
    #Init 
    def __init__(self, *args, **kwargs):
        
        #Call the super method to get the field set 
        super(OrderForm, self).__init__(*args, **kwargs)
        
        # Get the instance 
        instance = getattr(self, 'instance', None)
        
        # Set read only field 
        if instance and instance.pk:
            self.fields['order_number'].widget.attrs['readonly'] = True
            
        #Edit the required fields 
        self.fields['confirmation_number'].required = True
        self.fields['request_log_id'].required = True
    
    # Santiize read only input 
    def clean_order_number(self):
        
        # Get instance 
        instance = getattr(self, 'instance', None)
        
        if instance and instance.pk:
            return instance.order_number
        else:
            return self.cleaned_data['order_number']
    
    #Meta class 
    class Meta:
        
        #Model
        model = TaxiOrder 
        
        #Fields 
        fields = ['order_number', 'confirmation_number', 'request_log_id']

taxi_log/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy, reverse

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import TaxiOrder
from .forms import OrderForm

from django.utils import timezone

from .utils import render_to_pdf

from .filters import TaxiOrderFilter

# Create your views here.


# Update order view
class UpdateOrder(LoginRequiredMixin, generic.UpdateView):

    # Template
    template_name = 'taxi_log/create_order_form.html'

    # Form
    form_class = OrderForm
    #fields = ['order_number', 'confirmation_number', 'request_log_id']

    # Model
    model = TaxiOrder


# Create order redirect view
class CreateOrder(LoginRequiredMixin, generic.RedirectView):

    # Get redirect url method override
    def get_redirect_url(self, *args, **kwargs):
        
        # Query a set of objects from today
        order = None
        current_date = timezone.now().date()
        queryset = TaxiOrder.objects.filter(date_created__date=current_date)

        # If the queryset is empty, initialize a new object
        if not queryset:

            # Create an entry
            order_number = int(timezone.now().strftime('%m%d')) * 1000
            order = TaxiOrder(order_number=order_number,
                              user=self.request.user)

            # Save the instance
            order.save()

        # If object(s) already exists
        else:

            # Create an order and increment the order number from the previous entry
            order_number = str(queryset.last().order_number)

            # Split the order number and increment only the digits after the date
            # This will prevent still having the same date that will eventually increment to the point that the
            # entire order number will auto increment into the next date
            date = timezone.now().strftime('%m%d')
            lhs_order_number = order_number[:len(date)-1]
            print(lhs_order_number)
            rhs_order_number = '%04d' % (int(order_number[len(date)-1:]) + 1)

            order_number = int(lhs_order_number + rhs_order_number)

            # Create an order
            order = TaxiOrder(order_number=order_number,
                              user=self.request.user)

            # Save the instance
            order.save()
            
        # Redirect to update view
        return reverse('taxi_log:update_order', kwargs={'pk': order.pk})


# Order list view
class TaxiOrderList(LoginRequiredMixin, generic.ListView):

    # Template
    template_name = 'taxi_log/order_list_view.html'

    # Context dict
    def get_context_data(self, **kwargs):

        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Filter
        order_filter = TaxiOrderFilter(self.request.GET, queryset=TaxiOrder.objects.filter(
            request_log_id__isnull=False, confirmation_number__isnull=False))

        if self.request.GET.get('date_created'):
            # .filter(request_log_id__isnull=False, confirmation_number__isnull=False, date_created__date=timezone.now().date())
            taxiorder_list = order_filter.qs
        else:
            taxiorder_list = order_filter.qs.filter(
                request_log_id__isnull=False, confirmation_number__isnull=False, date_created__date=timezone.now().date())

        # Context variables
        queried_date = self.request.GET.get('date_created')

        # Set context data
        context['order_filter'] = order_filter
        context['taxiorder_list'] = taxiorder_list
        context['queried_date'] = queried_date if queried_date else timezone.now().date()

        return context

    def get_queryset(self):

        # Query for objects from today with non null entries
        current_date = timezone.now().date()
        query = TaxiOrder.objects.filter(
            request_log_id__isnull=False, confirmation_number__isnull=False, date_created__date=current_date)

        return query


# View current query as PDF
class TaxiOrderListPDF(LoginRequiredMixin, generic.View):

    # Get request to view the PDF
    def get(self, request, *args, **kwargs):

        # PDF html template
        template_name = 'taxi_log/order_list_pdf.html'

        # Query date
        query_date = self.kwargs['date'] if self.kwargs['date'] else timezone.now(
        ).date()

        # Query set
        taxiorder_list = TaxiOrder.objects.filter(
            request_log_id__isnull=False, confirmation_number__isnull=False, date_created__date=query_date)

        # Context dictionary
        context_dict = {'taxiorder_list': taxiorder_list,
                        'query_date': query_date}

        # Generate a pdf file for the query
        pdf = render_to_pdf(template_name, context_dict)

        # Return the response
        return pdf


# Download current query as a pdf
class TaxiOrderListPDFDownload(LoginRequiredMixin, generic.View):

    # Get request to view the PDF
    def get(self, request, *args, **kwargs):

        # PDF html template
        template_name = 'taxi_log/order_list_pdf.html'

        # Query date
        query_date = self.kwargs['date'] if self.kwargs['date'] else timezone.now(
        ).date()

        # Query set
        taxiorder_list = TaxiOrder.objects.filter(
            request_log_id__isnull=False, confirmation_number__isnull=False, date_created__date=query_date)

        # Context dictionary
        context_dict = {'taxiorder_list': taxiorder_list,
                        'query_date': query_date}

        # Generate a pdf file for the query
        pdf = render_to_pdf(template_name, context_dict)

        # Filename of the pdf --Formatted as "Taxi_Log_DATE.pdf"
        filename = 'Taxi_Log_{}.pdf'.format(query_date)

        # Set content disposition
        content = 'attachment; filename={}'.format(filename)
        pdf['Content-Disposition'] = content

        # Return the response
        return pdf

taxi_log/templates/taxi_log/create_order_form.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Order {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>Submit Order</h3>
            </div>
    
            <div class="card-body">
    
                <form action="" method="POST">
    
                    {% csrf_token %}
                    {{ form|crispy }}
    
                    <input class="btn btn-primary" type="submit" value='Submit'>
                    <a class="btn btn-danger" href="{% url 'taxi_log:order_list_view' %}">Cancel</a>
                </form>
    
            </div>
    
        </div>

    </div>
{% endblock %}

taxi_log/templates/taxi_log/order_list_pdf.html
<head>

    <style>
        @page {
            size: a4 portrait;
            
            @frame content_frame { 
                margin: 30px;
            }
        }

        table, th, td{
            border: 1px solid black;
            border-collapse: collapse;

            text-align: center;
            padding: 3px;
        }
    </style>

</head>

<body>

    <div id="header_content">
    	<h1>HCC</h1>
        <h2>Taxi log for: {{ query_date }}</h2>
        <p><small>Autogenerated PDF report</small></p>
    </div>

    <hr>
    <table>
        <thead> 
            <tr>
                <th>Request Log ID</th>
                <th>Order Number</th>
                <th>Confirmation Number</th>
                <th>Monitor</th>
            </tr>
        </thead>
    
        {% for order in taxiorder_list %}
    
            <tr>
                <td>{{ order.request_log_id }}</td>
                <td>{{ order.order_number }}</td>
                <td>{{ order.confirmation_number }}</td>
                <td>{{ order.user.username|upper }}</td>
            </tr>
    
        {% empty %}
            <tr>
                <td>No Current Orders</td>
            </tr>
        {% endfor %}
    </table>
</body>

taxi_log/templates/taxi_log/order_list_view.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Taxi Log {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>Taxi Log</h3>

                <br>
                <a class="btn btn-primary btn-sm" href="{% url 'taxi_log:create_order' %}">New Order</a>

                <br>
                {% if user.is_staff %}
                <hr>
                <h3>Filter Query</h3>

                    <form action="">
                        {% csrf_token %}
                        {{ order_filter.form|crispy }}

                    <input class="btn btn-primary btn-sm" type="submit" value="Submit">
                    </form>

                    <hr>
                    <a class="btn btn-primary btn-sm" href="{% url 'taxi_log:order_list_pdf_view' date=queried_date %}">View PDF</a>
                    <a class="btn btn-primary btn-sm" href="{% url 'taxi_log:order_list_pdf_download_view' date=queried_date %}">Download PDF</a>
                {% endif %}
            </div>
    
            <div class="card-body">
    
                <table class="table table-striped">
                    <thead class="thead-dark"> 
                        <tr>
                            <th>Request Log ID</th>
                            <th>Order Number</th>
                            <th>Confirmation Number</th>
                            <th>Monitor</th>
                        </tr>
                    </thead>

                    {% for order in taxiorder_list %}

                        <tr>
                            <td>{{ order.request_log_id }}</td>
                            <td>{{ order.order_number }}</td>
                            <td>{{ order.confirmation_number }}</td>
                            <td>{{ order.user.username|upper }}</td>
                        </tr>

                    {% empty %}
                        <tr>
                            <td>No Current Orders</td>
                        </tr>
                    {% endfor %}


                </table>
    
            </div>
    
        </div>

    </div>
{% endblock %}