accounts/urls.py
from django.urls import path
from .views import Login, RegisterUser, Logout

#Urls here 
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

devserver/urls.py
from django.contrib import admin
from django.views import generic
from django.urls import path, include
from django.contrib.auth.mixins import LoginRequiredMixin

# Home view
class Home(LoginRequiredMixin, generic.TemplateView):

    # Template
    template_name = 'devserver/home.html'


urlpatterns = [
    path('admin/', admin.site.urls),

    # Home url
    path('', Home.as_view(), name='home'),

    # Admin dashboard
    path('admin_dashboard/', include('admin_dashboard.urls', namespace='admin_dashboard')),

    # Accounts URLS
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # File upload
    path('file_upload/', include('file_upload.urls', namespace='file_upload')),

    # File download
    path('file_download/', include('file_download.urls', namespace='file_download')),

    # Taxi Log
    path('taxi_log/', include('taxi_log.urls', namespace='taxi_log')),

    # API endpoints for use by the form creator 
    path('api/', include('form_creator_api.urls', namespace='form_creator_api'))
]

form_creator_api/urls.py
from . import views 
from django.urls import path 
from django.contrib.admin.views.decorators import staff_member_required

# app name 
app_name = 'form_creator_api'

urlpatterns = [
    
    # Endpoints
    path('', views.APIOverview.as_view(), name='api_overview'),
    path('safeway_list/', views.SafewayLocationList.as_view(), name='safeway_list_api'),
    path('request_log_url/', views.RequestLogDetail.as_view(), name='request_log_api'),
    path('uploaded_files/<str:endpoint_name>/', views.UploadedFileDetail.as_view(), name='uploaded_files_api'),
    
    # Form views and template views
    path('control_panel/', staff_member_required( views.APIControlPanel.as_view() ), name='api_control_panel'),
    path('new_location/', staff_member_required( views.CreateSafewayLocation.as_view() ), name='create_safeway_location'),
    path('update_location/<int:pk>/', staff_member_required( views.UpdateSafewayLocation.as_view() ), name='update_safeway_location'),
    path('delete_location/<int:pk>/', staff_member_required( views.DeleteSafewayLocation.as_view() ), name='delete_safeway_location'),
    path('update_request_log_url/<int:pk>/', staff_member_required( views.UpdateRequestLogURL.as_view() ), name='update_request_log_url')
]

form_creator_api/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.urls import reverse 

# Create your models here

# Safeway location model 
class SafewayLocation(models.Model):
    
    # Location name 
    location_name = models.CharField(max_length=255, blank=False, null=False, unique=True)
    
    # Fax number 
    # TODO --Might need a more specialized external phone library to validate
    # but it shouldnt matter for now (?), will see how user testing goes
    fax_number = models.CharField(max_length=255, blank=False, null=False, unique=True)
    
    #  User who made this 
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    
    # Redirect
    def get_absolute_url(self):
        return reverse('form_creator_api:api_control_panel')
    
    # String representation 
    def __str__(self):
        return self.location_name
    
# Request Log URL model
# Singleton model, should only have 1 instance ever 
class RequestLogURL(models.Model):
    
    # URL 
    url = models.CharField(max_length=400, blank=False, null=False, unique=True)
    
    # User who made this 
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    
    # Override save method 
    def save(self, *args, **kwargs):
        
        # Ensure the pk does not exist for the object we want to add
        # and object exist in the database 
        if not self.pk and RequestLogURL.objects.exists():
            
            # Raise a validation error 
            raise ValidationError("Only one instance of this model is allowed!")
        
        # Call super save method 
        return super(RequestLogURL, self).save(*args, **kwargs)
    
    # Redirect
    def get_absolute_url(self):
        return reverse('form_creator_api:api_control_panel')
    
    # String representation 
    def __str__(self):
        return self.url
        

form_creator_api/forms.py
from django.forms import ModelForm, HiddenInput
from .models import SafewayLocation, RequestLogURL

# Create new safeway location form
class NewLocationForm(ModelForm):
    
    class Meta: 
        
        # Model 
        model = SafewayLocation
        
        # Fields 
        fields = ['location_name', 'fax_number', 'user']
        
        # Hidden fields 
        widgets = {
            'user' : HiddenInput(),
        }

form_creator_api/views.py
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404

# DRF Imports 
from rest_framework.views import APIView 
from rest_framework.response import Response

# Serializers 
from .serializers import *

# Form
from .forms import NewLocationForm

#Import model
from .models import SafewayLocation, RequestLogURL
from file_upload.models import File

# Create your views here.

##########################################################
# API Response views 
##########################################################

# Api overview page 
class APIOverview(APIView):
    
    # Get request 
    def get(request, *args, **kwargs):
        
        # List of endpoints 
        api_endpoints = {
            'Safeway List' : '/safeway_list/',
            'Request Log URL' : '/request_log_url/',
            'Uploaded File Detail' : '/uploaded_files/<str:endpoint_name>'
        }
        
        # Return the response 
        return Response(api_endpoints)

# SafewayLocation List api view 
class SafewayLocationList(APIView):
    
    # Get request 
    def get(request, *args, **kwargs):
        
        # Query all objects 
        safeway_list = SafewayLocation.objects.all()
        
        # Serialize the model 
        serializer = SafewayLocationSerializer(safeway_list, many=True)
        
        # Return the serialized data 
        return Response(serializer.data)
    
# RequestLogURL api view 
class RequestLogDetail(APIView):
    
    # Get request 
    def get(self, *args, **kwargs):
        
        # Query the object 
        request_log_url = RequestLogURL.objects.first()
        
        # Serializer 
        serializer = RequestLogURLSerializer(request_log_url, many=False)
        
        # Return serialized data 
        return Response(serializer.data)
    
# Uploaded file api view
class UploadedFileDetail(APIView):
    
    # Get request 
    def get(self, *args, **kwargs):
        
        # Query provided object
        endpoint_name = self.kwargs['endpoint_name']
        uploaded_files = get_object_or_404(File, endpoint_name=endpoint_name)
        
        # Serialize the model 
        serializer = UploadedFileSerializer(uploaded_files, many=False)
        
        # Return serialized data 
        return Response(serializer.data)


##########################################################
# Model CRUD views
##########################################################

# API Home view 
class APIControlPanel(LoginRequiredMixin, generic.TemplateView):
    
    # Template
    template_name = 'form_creator_api/api_home_view.html'
    
    # Context dictionary 
    def get_context_data(self, *args, **kwargs):
        
         # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Pass in model objects into context 
        context['request_log_url'] = RequestLogURL.objects.first()
        context['safeway_location_list'] = SafewayLocation.objects.all()
        
        return context

# Create a new Safeway location
class CreateSafewayLocation(LoginRequiredMixin, generic.CreateView):
    
    # Template 
    template_name = 'form_creator_api/create_safeway_location.html'
    
    # Form 
    form_class = NewLocationForm
    
    # Model 
    model = SafewayLocation
    
    #Set field instances
    def get_initial(self):
        
        #Call super method 
        initial = super().get_initial()
        
        #Set user 
        initial['user'] = self.request.user
        
        return initial
    
# Update safeway location 
class UpdateSafewayLocation(LoginRequiredMixin, generic.UpdateView):
    
    # Template 
    template_name = 'form_creator_api/update_safeway_location.html'
    
    # Fields 
    fields = ['location_name', 'fax_number']
    
    # Model 
    model = SafewayLocation
    
# Delete safway location
class DeleteSafewayLocation(LoginRequiredMixin, generic.DeleteView):
    
    # Template 
    template_name = 'form_creator_api/confirm_delete.html'
    
    # Model 
    model = SafewayLocation
    
    # Redirect 
    def get_success_url(self):
        return reverse('form_creator_api:api_control_panel')
    
# Update Request Log URL
class UpdateRequestLogURL(LoginRequiredMixin, generic.UpdateView):
    
    # Template 
    template_name = 'form_creator_api/update_request_log_url.html'
    
    # Model 
    model = RequestLogURL
    
    # Fields 
    fields = ['url']

form_creator_api/templates/form_creator_api/api_home_view.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} New Location {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <br>
    <div class="container">

        <div class="card">
            <div class="card-header">
                <h3>Current Request Log URL</h3>
            </div>

            <div class="card-body">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th>URL</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tr>
                        {% if request_log_url.pk %}
                            <td>{{ request_log_url }}</td>
                            <td><a class="btn btn-primary" href="{% url 'form_creator_api:update_request_log_url' pk=request_log_url.pk %}">Edit</a></td>
                        {% else %}
                            <td><h4>No entry</h4></td>
                        {% endif %}
                    </tr>
                </table>
            </div>
        </div>

        <br>

        <div class="card">
            <div class="card-header">
                <h3>Safeway Locations</h3>
                <hr>
                <a class="btn btn-primary" href="{% url 'form_creator_api:create_safeway_location' %}">Create</a>
            </div>

            <div class="card-body">
                <table class="table table-striped">

                    <thead class="thead-dark">
                        <tr>
                            <th>Location</th>
                            <th>Fax Number</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>

                    {% for location in safeway_location_list %}
                        <tr>
                            <td> {{ location.location_name }} </td>
                            <td> {{ location.fax_number }} </td>
                            <td><a class="btn btn-primary" href="{% url 'form_creator_api:update_safeway_location' pk=location.pk %}">Edit</a></td>
                            <td><a class="btn btn-danger" href="{% url 'form_creator_api:delete_safeway_location' pk=location.pk %}">Delete</a></td>
                        </tr>
                    {% endfor %}

                </table>
            </div>
        </div>

    </div>

{% endblock %}

form_creator_api/templates/form_creator_api/confirm_delete.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Delete Location {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>Delete {{ safewaylocation }}?</h3>
            </div>

            <div class="card-body">

                <form action="" method="POST">

                    {% csrf_token %}

                    <input class="btn btn-primary" type="submit" value="Submit">
                    <a class="btn btn-danger" href="{% url 'form_creator_api:api_control_panel' %}">Cancel</a>
                </form>

            </div>

        </div>

    </div>

{% endblock %}

form_creator_api/templates/form_creator_api/create_safeway_location.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} New Location {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>Create New Location</h3>
            </div>

            <div class="card-body">

                <form action="" method="POST">

                    {% csrf_token %}
                    {{ form|crispy }}

                    <input class="btn btn-primary" type="submit" value="Submit">
                    <a class="btn btn-danger" href="{% url 'form_creator_api:api_control_panel' %}">Cancel</a>
                </form>

            </div>

        </div>

    </div>

{% endblock %}

form_creator_api/templates/form_creator_api/update_request_log_url.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Update URL {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>Update URL</h3>
            </div>

            <div class="card-body">

                <form action="" method="POST">

                    {% csrf_token %}
                    {{ form|crispy }}

                    <input class="btn btn-primary" type="submit" value="Submit">
                    <a class="btn btn-danger" href="{% url 'form_creator_api:api_control_panel' %}">Cancel</a>
                </form>

            </div>

        </div>

    </div>

{% endblock %}

form_creator_api/templates/form_creator_api/update_safeway_location.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Update Location {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block body %}

    <div class="container">

        <div class="card">

            <div class="card-header">
                <h3>Update Location</h3>
            </div>

            <div class="card-body">

                <form action="" method="POST">

                    {% csrf_token %}
                    {{ form|crispy }}

                    <input class="btn btn-primary" type="submit" value="Submit">
                    <a class="btn btn-danger" href="{% url 'form_creator_api:api_control_panel' %}">Cancel</a>
                </form>

            </div>

        </div>

    </div>

{% endblock %}