accounts/urls.py
from django.urls import path
from .views import Login, RegisterUser, Logout

#Urls here 
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

admin_dashboard/urls.py
from django.urls import path, include
from . import views
from django.contrib.admin.views.decorators import staff_member_required

app_name = 'admin_dashboard'

urlpatterns = [
    path('', staff_member_required( views.AdminDashboard.as_view() ), name='admin_dashboard_view'),
    path('details/<str:username>/all_orders/', staff_member_required( views.UserTaxiOrderList.as_view() ), name='user_order_list_view')
]

devserver/urls.py
from django.contrib import admin
from django.views import generic
from django.urls import path, include
from django.contrib.auth.mixins import LoginRequiredMixin

# Home view
class Home(LoginRequiredMixin, generic.TemplateView):

    # Template
    template_name = 'devserver/home.html'


urlpatterns = [
    path('admin/', admin.site.urls),

    # Home url
    path('', Home.as_view(), name='home'),

    # Admin dashboard
    path('admin_dashboard/', include('admin_dashboard.urls', namespace='admin_dashboard')),

    # Accounts URLS
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # File upload
    path('file_upload/', include('file_upload.urls', namespace='file_upload')),

    # File download
    path('file_download/', include('file_download.urls', namespace='file_download')),

    # Taxi Log
    path('taxi_log/', include('taxi_log.urls', namespace='taxi_log')),

    # API endpoints for use by the form creator 
    path('api/', include('form_creator_api.urls', namespace='form_creator_api'))
]

file_upload/urls.py
from django.urls import path, include
from .views import UploadFile, UpdateFileDetails, UpdateFile, DeleteFile, FileList, FileDetail

app_name = 'file_upload'

urlpatterns = [
    
    #CRUD Views
    path('upload/', UploadFile.as_view(), name='upload_file'),
    path('update_file/<slug:slug>/', UpdateFile.as_view(), name='update_file'),
    path('update_file_details/<slug:slug>/', UpdateFileDetails.as_view(), name='update_file_details'),
    path('delete_file/<slug:slug>', DeleteFile.as_view(), name='delete_file'),
    
    #Views 
    path('file_list/', FileList.as_view(), name='file_list'),
    path('file/<slug:slug>/', FileDetail.as_view(), name='file_detail')
]

form_creator_api/urls.py
from . import views 
from django.urls import path 
from django.contrib.admin.views.decorators import staff_member_required

# app name 
app_name = 'form_creator_api'

urlpatterns = [
    
    # Endpoints
    path('', views.APIOverview.as_view(), name='api_overview'),
    path('safeway_list/', views.SafewayLocationList.as_view(), name='safeway_list_api'),
    path('request_log_url/', views.RequestLogDetail.as_view(), name='request_log_api'),
    path('uploaded_files/<str:endpoint_name>/', views.UploadedFileDetail.as_view(), name='uploaded_files_api'),
    
    # Form views and template views
    path('control_panel/', staff_member_required( views.APIControlPanel.as_view() ), name='api_control_panel'),
    path('new_location/', staff_member_required( views.CreateSafewayLocation.as_view() ), name='create_safeway_location'),
    path('update_location/<int:pk>/', staff_member_required( views.UpdateSafewayLocation.as_view() ), name='update_safeway_location'),
    path('delete_location/<int:pk>/', staff_member_required( views.DeleteSafewayLocation.as_view() ), name='delete_safeway_location'),
    path('update_request_log_url/<int:pk>/', staff_member_required( views.UpdateRequestLogURL.as_view() ), name='update_request_log_url')
]

taxi_log/urls.py
from . import views 
from django.urls import path

app_name = 'taxi_log'

urlpatterns = [
    path('', views.TaxiOrderList.as_view(), name='order_list_view'),
    path('order/', views.CreateOrder.as_view(), name='create_order'),
    path('order/<int:pk>/', views.UpdateOrder.as_view(), name='update_order'),
    path('pdf_view/<str:date>/', views.TaxiOrderListPDF.as_view(), name='order_list_pdf_view'),
    path('pdf_download/<str:date>/', views.TaxiOrderListPDFDownload.as_view(), name='order_list_pdf_download_view')
]

templates/devserver/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />

    <!-- Base stylesheets -->
    <link rel="stylesheet" href="{% static 'devserver/css/base.css' %}">

    <!-- External stylesheets -->
    {% block stylesheet %}{% endblock %}

    <!-- Title -->
    <title>HCC |{% block title %}{% endblock %}</title>
  </head>

  <body>
    {% include 'devserver/navbar.html' %}
    {% block body %}{% endblock %}
  </body>

</html>

templates/devserver/home.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Home {% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'devserver/css/home.css' %}">
{% endblock %}

{% block body %}

    <div class="jumbotron">
        <h1>Site Pages</h1>
    </div>

    <div class="container" id="navigation-cards">

        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'file_upload:file_list' %}">Downloads</a></h3>
            </div>

            <div class="card-body">
                <p class="card-text">Download software here</p>
            </div>
        </div>

        <br>
        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'taxi_log:order_list_view' %}">Taxi Log</a></h3>
            </div>
            
            <div class="card-body">
                <p class="card-text">Generate and input order numbers here</p>
            </div>
        </div>

        {% if user.is_staff %}
        <br>
        <div class="card">
            <div class="card-header">
                <h3><a href="{% url 'form_creator_api:api_control_panel' %}">Form Creator API</a></h3>
            </div>

            <div class="card-body">
                <p class="card-text">Control panel for the Form Creator API</p>
            </div>
        </div>
        {% endif %}
        
    </div>

{% endblock %}

templates/devserver/navbar.html
{% load static %}

<link rel="stylesheet" href="{% static 'devserver/css/navbar.css' %}">

<nav class="navbar navbar-expand-lg" id='navbar-menu'>

    <a class='navbar-brand' href="{% url 'home' %}" id='brand'>HCC</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id='navbarSupportedContent'>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>

            {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin_dashboard:admin_dashboard_view' %}">Admin</a>
                </li>
            {% endif %}
        </ul>

        <ul class='navbar-nav ml-auto'>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <p class="nav-link disabled" id='welcome-link'>Welcome {{user.username}}</p>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}" id='logout-link'>Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
                </li>
            {% endif %}
        </ul>

    </div>

</nav>  