accounts/urls.py
from django.urls import path
from .views import Login, RegisterUser, Logout

#Urls here 
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

devserver/urls.py
from django.contrib import admin
from django.views import generic
from django.urls import path, include
from django.contrib.auth.mixins import LoginRequiredMixin

# Home view
class Home(LoginRequiredMixin, generic.TemplateView):

    # Template
    template_name = 'devserver/home.html'


urlpatterns = [
    path('admin/', admin.site.urls),

    # Home url
    path('', Home.as_view(), name='home'),

    # Admin dashboard
    path('admin_dashboard/', include('admin_dashboard.urls', namespace='admin_dashboard')),

    # Accounts URLS
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # File upload
    path('file_upload/', include('file_upload.urls', namespace='file_upload')),

    # File download
    path('file_download/', include('file_download.urls', namespace='file_download')),

    # Taxi Log
    path('taxi_log/', include('taxi_log.urls', namespace='taxi_log')),

    # API endpoints for use by the form creator 
    path('api/', include('form_creator_api.urls', namespace='form_creator_api'))
]

file_download/urls.py
from django.urls import path
from . import views

app_name = 'file_download'

urlpatterns = [
    path('download/<slug:slug>/', views.FileDownload.as_view(), name='download_file')
]

file_upload/urls.py
from django.urls import path, include
from .views import UploadFile, UpdateFileDetails, UpdateFile, DeleteFile, FileList, FileDetail

app_name = 'file_upload'

urlpatterns = [
    
    #CRUD Views
    path('upload/', UploadFile.as_view(), name='upload_file'),
    path('update_file/<slug:slug>/', UpdateFile.as_view(), name='update_file'),
    path('update_file_details/<slug:slug>/', UpdateFileDetails.as_view(), name='update_file_details'),
    path('delete_file/<slug:slug>', DeleteFile.as_view(), name='delete_file'),
    
    #Views 
    path('file_list/', FileList.as_view(), name='file_list'),
    path('file/<slug:slug>/', FileDetail.as_view(), name='file_detail')
]

file_upload/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete, pre_save

import ntpath

# Create your models here.

#User directory path 
def user_directory_path(instance, filename):
    return 'uploads/{}'.format(filename)

#File model for uploaded files 
class File(models.Model):
    
    #File 
    uploaded_file = models.FileField(upload_to=user_directory_path, blank=False, null=False)
    
    #Filename 
    file_name = models.CharField(max_length=255, blank=True, null=True)
    
    # Endpoint name 
    endpoint_name = models.CharField(max_length=255, blank=False, null=False, unique=True)
    
    #Version 
    version = models.CharField(max_length=255, blank=True, null=True)

    #Slug field 
    slug = models.SlugField(max_length=255, blank=True, null=True, unique=True)
    
    #Description 
    description = models.TextField(blank=False, null=False)
    
    #Upload date 
    upload_date = models.DateTimeField(auto_now_add=True)
    
    #User who uploaded the file 
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    
    #Override save method 
    def save(self, *args, **kwargs):
        
        #If this model entry does not exist yet
        if not self.pk:
            
            #Set the file name --split the file path and get the file name 
            self.file_name = ntpath.basename(self.uploaded_file.name).split('.')[0]
            
        #Set the slug of the file --set to format FILE-NAME-VERSION
        #ex: file-name-1-23-4
        text = self.file_name + '-' + self.version
        self.slug = slugify(text)
        
        #Call super save method 
        super(File, self).save(*args, **kwargs)
        
    #Absoulte URL 
    def get_absolute_url(self):
        return reverse_lazy('file_upload:file_detail', kwargs={'slug' : self.slug})
        
    
    #str representation
    def __str__(self):
        return self.file_name



#Connect signals 
from .signals import pre_save_file, delete_linked_file

#Connect pre save
pre_save.connect(pre_save_file, sender=File)

#Connect pre delete
pre_delete.connect(delete_linked_file, sender=File)

file_upload/forms.py
from django.forms import ModelForm, FileField, ValidationError, HiddenInput
from django.forms.widgets import FileInput
from .models import File

# Form to upload a file and create a new model
class UploadFileForm(ModelForm):

    class Meta:

        # Model
        model = File

        # Fields
        fields = ('uploaded_file', 'endpoint_name', 'description', 'version', 'user')

        # Widgets
        widgets = {
            'uploaded_file': FileInput(),
            'user' : HiddenInput(),
        }

    # Clean the file field
    def clean_uploaded_file(self):

        # Get the file and validate it
        file = self.cleaned_data['uploaded_file']

        # File extension
        ext = file.name.split('.')[-1].lower()
        print(ext)

        # Allowed file types
        allowed_types = ['exe', 'rar', 'zip']

        # Make sure the file is an exe
        if ext not in allowed_types:
            raise ValidationError(
                'This is not a supported file type. Supported file types: exe, rar, zip')

        return file
    
    #Update the file 
class UpdateFileForm(ModelForm):

    class Meta:

        # Model
        model = File

        # Fields
        fields = ('uploaded_file', 'endpoint_name', 'description', 'version')

        # Widgets
        widgets = {
            'uploaded_file': FileInput()
        }

    # Clean the file field
    def clean_uploaded_file(self):

        # Get the file and validate it
        file = self.cleaned_data['uploaded_file']

        # File extension
        ext = file.name.split('.')[-1].lower()

        # Allowed file types
        allowed_types = ['exe', 'rar', 'zip']

        # Make sure the file is an exe
        if ext not in allowed_types:
            raise ValidationError(
                'This is not a supported file type. Supported file types: exe, rar, zip')

        return file

file_upload/views.py
from django.shortcuts import render
from django.urls import reverse
from .forms import UpdateFileForm, UploadFileForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from .models import File

# Create your views here.

#############################
# Generic Views
#############################

#File list view 
class FileList(generic.ListView):
    
    #Model 
    model = File 
    
    #Template 
    template_name = 'file_upload/file_list_view.html'
    
#File detail view 
class FileDetail(LoginRequiredMixin, generic.DetailView):
    
    #Model
    model = File 
    
    #Template 
    template_name = 'file_upload/file_detail_view.html'

#############################
# CRUD Views
#############################

#Upload file view
class UploadFile(generic.CreateView):
    
    #Form
    form_class = UploadFileForm
    
    #Model 
    model = File 
    
    #Template
    template_name = 'file_upload/file_upload_view.html'
    
    #Set field instances
    def get_initial(self):
        
        #Call super method 
        initial = super().get_initial()
        
        #Set user 
        initial['user'] = self.request.user
        
        return initial
    
#Update file view 
class UpdateFile(generic.UpdateView):
    
    #Form
    form_class = UpdateFileForm
    
    #Model 
    model = File 
    
    #Template 
    template_name = 'file_upload/update_file_view.html'

#Update file details view 
class UpdateFileDetails(generic.UpdateView):
    
    #Model 
    model = File 
    
    #Fields 
    fields = ['file_name', 'description', 'version']
    
    #Template
    template_name = 'file_upload/update_file_details_view.html'
    
#Delete file view 
class DeleteFile(generic.DeleteView):
    
    #Model 
    model = File 
    
    #Template
    template_name = 'file_upload/delete_file_view.html'
    
    #Redirect to home page 
    def get_success_url(self):
        return reverse('home')
    

file_upload/templates/file_upload/delete_file_view.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Delete {% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="">
{% endblock %}

{% block body %}

    <br>
    <div class="container" id="file-upload-card">

        <div class="card" id="file-upload-card">

            <div class="card-header">
                <h3><strong>Delete File</strong></h3>
            </div>

            <div class="card-body">
                <form action="{% url 'file_upload:delete_file' slug=file.slug %}" method="POST">

                    {% csrf_token %}
                    <h3>Are you sure you want to delete {{ file.file_name }}?</h3>
                    
                    <hr>
                    <h5><strong>File Details</strong></h5>
                    <p>File Name: {{ file.file_name }}.exe</p>
                    <p>File Path: {{ file.uploaded_file.path }}</p>
                    <p>Upload Date: {{ file.upload_date }}</p>
                    <p>Version: {{ file.version }}</p>

                    <hr>
                    <input class="btn btn-danger" type="submit" value="Delete">
                    <a class="btn btn-warning" href="{% url 'file_upload:file_list' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

file_upload/templates/file_upload/file_detail_view.html
{% extends 'devserver/base.html' %} 
{% load static %} 
{% block title %} {{file.file_name }} {% endblock %} 

{% block stylesheet %}
    <link rel="stylesheet" href="" />
{% endblock %} 

{% block body %}

<div class="container" id="file-detail-card">
  <div class="card">

    <div class="card-header">
      <h3>{{ file.file_name|title }}</h3>
      <h5><small>Version: {{ file.version }}</small></h5>

      <hr>
      {% if user.is_superuser %}
        <a class="btn btn-sm btn-warning" href="{% url 'file_upload:update_file_details' slug=file.slug %}">Edit Details</a>
        <a class="btn btn-sm btn-primary" href="{% url 'file_upload:update_file' slug=file.slug %}">Upload New File</a>
        <a class="btn btn-sm btn-danger" href="{% url 'file_upload:delete_file' slug=file.slug %}">Delete</a>
      {% endif %}

      {% if user.is_authenticated %}
        <a class="btn btn-sm btn-primary" href="{% url 'file_download:download_file' slug=file.slug %}">Download</a>
      {% endif %}
    </div>

    <div class="card-body">
      <p>{{ file.description|safe|linebreaks }}</p>
    </div>

    <div class="card-footer text-muted">
      <p><small>Uploaded {{ file.upload_date|timesince }} ago by {{ file.user|title}}</small></p>
    </div>

  </div>
</div>
{% endblock %}

file_upload/templates/file_upload/file_list_view.html
{% extends 'devserver/base.html' %}
{% load static %}

{% block title %} Downloads {% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="">
{% endblock %}

{% block body %}

    <div class="jumbotron">
        <h1>Downloads</h1>

        <br>
	{% if user.is_superuser  %}
        	<a class="btn btn-primary" href="{% url 'file_upload:upload_file' %}">Upload</a>
	{% endif  %}
    </div>

    <div class="container" id="file-list-cards">

        {% for file in file_list %}

            <div class="card">

                <div class="card-header">
                    <h3><a href="{% url 'file_upload:file_detail' slug=file.slug %}">{{ file.file_name|title }}</a></h3>
                    {% if user.is_superuser %}
                        <a class="btn btn-sm btn-warning" href="{% url 'file_upload:update_file_details' slug=file.slug %}">Edit Details</a>
                        <a class="btn btn-sm btn-primary" href="{% url 'file_upload:update_file' slug=file.slug %}">Upload New File</a>
                        <a class="btn btn-sm btn-danger" href="{% url 'file_upload:delete_file' slug=file.slug %}">Delete</a>
                    {% elif user.is_authenticated %}
                        
                    {% endif %}
                </div>

                <div class="card-body">
                    <p>{{ file.description|truncatechars:255|safe|linebreaks }}</p>
                </div>

                <div class="card-footer text-muted">
                    <p><small>Uploaded {{ file.upload_date|timesince }} ago by {{ file.user|title }}</small></p>
                </div>

            </div>

        {% empty %}

            <div class="card" id='empty-card'>
                <div class="card-body">
                    <h4>There are currently no files uploaded</h4>
                </div>
            </div>

        {% endfor %}

    </div>

{% endblock %}

file_upload/templates/file_upload/file_upload_view.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Upload {% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="">
{% endblock %}

{% block body %}

    <br>
    <div class="container" id="file-upload-card">

        <div class="card" id="file-upload-card">

            <div class="card-header">
                <h3><strong>Upload File</strong></h3>
            </div>

            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form|crispy }}
    
                    <input class="btn btn-primary" type="submit" value="Upload">
                    <a class="btn btn-danger" href="{% url 'file_upload:file_list' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

file_upload/templates/file_upload/update_file_details_view.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Upload {% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="">
{% endblock %}

{% block body %}

    <br>
    <div class="container" id="file-upload-card">

        <div class="card" id="file-upload-card">

            <div class="card-header">
                <h3><strong>Edit File</strong></h3>
            </div>

            <div class="card-body">
                <form action="" method="POST">

                    {% csrf_token %}
                    {{ form|crispy }}
    
                    <input class="btn btn-primary" type="submit" value="Update">
                    <a class="btn btn-danger" href="{% url 'file_upload:file_list' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

file_upload/templates/file_upload/update_file_view.html
{% extends 'devserver/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Upload {% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="">
{% endblock %}

{% block body %}

    <br>
    <div class="container" id="file-upload-card">

        <div class="card" id="file-upload-card">

            <div class="card-header">
                <h3><strong>Update File</strong></h3>
            </div>

            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">

                    {% csrf_token %}

                    <p>Current file: {{ file.uploaded_file.path }}</p>

                    {{ form|crispy }}
    
                    <input class="btn btn-primary" type="submit" value="Update">
                    <a class="btn btn-danger" href="{% url 'file_upload:file_list' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}